export const GET_USERS_REQUEST = 'user/GET_USERS_REQUEST'
export const GET_USERS_SUCCESS = 'user/GET_USERS_SUCCESS'
export const GET_CURRENT_USER_REQUEST = 'user/GET_CURRENT_USER_REQUEST'
export const GET_CURRENT_USER_SUCCESS = 'user/GET_CURRENT_USER_SUCCESS'
