export const GET_CHATS_REQUEST = 'chat/GET_CHATS_REQUEST'
export const GET_CHATS_SUCCESS = 'chat/GET_CHATS_SUCCESS'

export const RECEIVE_CHAT_SUCCESS = 'chat/RECEIVE_CHAT_SUCCESS'

export const CREATE_MESSAGE_REQUEST = 'chat/GET_MESSAGE_REQUEST'

export const RECEIVE_MESSAGE_SUCCESS = 'chat/RECEIVE_MESSAGE_SUCCESS'

export const CREATE_CHAT_REQUEST = 'chat/CREATE_CHAT_REQUEST'
